version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@httptoolkit/osx-find-executable'
      - dependency-name: standard
